[theme]
primaryColor      = "#e10600"
backgroundColor   = "#000000"
secondaryBackgroundColor = "#050505"
textColor         = "#00ff87"
font              = "monospace"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
