[theme]
primaryColor      = "#e10600"
backgroundColor   = "#0a0c10"
secondaryBackgroundColor = "#121620"
textColor         = "#ffffff"
font              = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
